name: Area 51 Machine Design
favicon: null
layout_spectrum: 0.2475
typography_spectrum: 0.26247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4375
  lightness: 0.6578407613560557
  saturation: 0.7759613548405468
  rhythmicContrast: 0.21279325964860618
purpose: []
